service: apiFunctions

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-northeast-1
  memorySize: 128

functions:
  hello:
    handler: handler.hello

    events:
      - http:
          path: users/create
          method: get
          # need api key auth?
          # if on, you need to assign apiKey using plan
          private: true

  slack-say:
    handler: handler.slack_say

    events:
      - http:
          path: slack/say
          method: get
          # need api key auth?
          # if on, you need to assign apiKey using plan
          # parameters:
          #   channel: slack channel
          #   message: slack message
          private: true

